/** Dil kodu -> ulke kodu (SVG bayrak icin country-flag-icons) */
export const LANGUAGE_TO_COUNTRY: Record<string, string> = {
  en: 'GB',
  hu: 'HU',
  cs: 'CZ',
  ko: 'KR',
  it: 'IT',
  nl: 'NL',
  uk: 'UA',
  vi: 'VN',
  pl: 'PL',
  de: 'DE',
  'pt-BR': 'BR',
  pt: 'BR',
  th: 'TH',
  tr: 'TR',
  ro: 'RO',
  'zh-TW': 'TW',
  zh: 'TW',
  'zh-CN': 'CN',
  ru: 'RU',
  'es-419': 'MX',
  'es-ES': 'ES',
  es: 'ES',
  fr: 'FR',
  sv: 'SE',
  ja: 'JP',
  ar: 'SA',
  hr: 'HR',
  cnr: 'ME',
}

/** Mesaj dili secenekleri (hos geldin, hoscakal vb.) - bayrakli select icin */
export const MESSAGE_LANGUAGES = [
  { code: 'en', label: 'English (US)', countryCode: 'GB' },
  { code: 'hu', label: 'Magyar', countryCode: 'HU' },
  { code: 'cs', label: '\u010Ce\u0161tina', countryCode: 'CZ' },
  { code: 'ko', label: '\uD55C\uAD6D\uC5B4', countryCode: 'KR' },
  { code: 'it', label: 'Italiano', countryCode: 'IT' },
  { code: 'nl', label: 'Nederlands', countryCode: 'NL' },
  { code: 'uk', label: '\u0423\u043A\u0440\u0430\u0457\u043D\u0441\u044C\u043A\u0430', countryCode: 'UA' },
  { code: 'vi', label: 'Ti\u1EBFng Vi\u1EC7t', countryCode: 'VN' },
  { code: 'pl', label: 'Polski', countryCode: 'PL' },
  { code: 'de', label: 'Deutsch', countryCode: 'DE' },
  { code: 'pt-BR', label: 'Portugu\u00EAs (Brasil)', countryCode: 'BR' },
  { code: 'th', label: '\u0E44\u0E17\u0E22', countryCode: 'TH' },
  { code: 'tr', label: 'T\u00FCrk\u00E7e', countryCode: 'TR' },
  { code: 'ro', label: 'Rom\u00E2n\u0103', countryCode: 'RO' },
  { code: 'zh-TW', label: '\u7E41\u9AD4\u4E2D\u6587', countryCode: 'TW' },
  { code: 'ru', label: '\u0420\u0443\u0441\u0441\u043A\u0438\u0439', countryCode: 'RU' },
  { code: 'es-419', label: 'Espa\u00F1ol (Latinoam\u00E9rica)', countryCode: 'MX' },
  { code: 'es-ES', label: 'Espa\u00F1ol (Espa\u00F1a)', countryCode: 'ES' },
  { code: 'fr', label: 'Fran\u00E7ais', countryCode: 'FR' },
  { code: 'sv', label: 'Svenska', countryCode: 'SE' },
  { code: 'zh-CN', label: '\u7B80\u4F53\u4E2D\u6587', countryCode: 'CN' },
  { code: 'ja', label: '\u65E5\u672C\u8A9E', countryCode: 'JP' },
  { code: 'ar', label: '\u0627\u0644\u0639\u0631\u0628\u064A\u0629', countryCode: 'SA' },
  { code: 'hr', label: 'Hrvatski', countryCode: 'HR' },
  { code: 'cnr', label: 'Crnogorski', countryCode: 'ME' },
] as const

export type MessageLanguageCode = (typeof MESSAGE_LANGUAGES)[number]['code']
