export const LANDING_FEATURES = [
  {
    slug: 'poll',
    titleKey: 'featurePoll',
    descKey: 'featurePollDesc',
    name: 'Anket',
    description: 'Kolayca anket oluşturun ve topluluk görüşlerini toplayın.',
  },
  {
    slug: 'reminder',
    titleKey: 'featureReminder',
    descKey: 'featureReminderDesc',
    name: 'Hatırlatıcı',
    description: 'Önemli tarihleri ve etkinlikleri hatırlatıcı ile takip edin.',
  },
  {
    slug: 'reaction-role',
    titleKey: 'featureReactionRole',
    descKey: 'featureReactionRoleDesc',
    name: 'Tepki Rolü',
    description: 'Emoji ile otomatik rol verme sistemi kurun.',
  },
  {
    slug: 'temporary-voice',
    titleKey: 'featureVoice',
    descKey: 'featureVoiceDesc',
    name: 'Geçici Ses Kanalı',
    description: 'Ses kanallarını kilitleyin, gizleyin, limit koyun ve daha fazlasını yönetin.',
  },
  {
    slug: 'ticket',
    titleKey: 'featureTicket',
    descKey: 'featureTicketDesc',
    name: 'Ticket Paneli',
    description: 'Destek talepleri için otomatik ticket kanalları oluşturun.',
  },
  {
    slug: 'birthday',
    titleKey: 'featureBirthday',
    descKey: 'featureBirthdayDesc',
    name: 'Doğum Günü',
    description: 'Üyelerinizin doğum günlerini otomatik kutlayın.',
  },
  {
    slug: 'logs',
    titleKey: 'featureLog',
    descKey: 'featureLogDesc',
    name: 'Log Kanalı',
    description: 'Sunucu olaylarını detaylı log kanallarında takip edin.',
  },
  {
    slug: 'custom-command',
    titleKey: 'featureCustomCommand',
    descKey: 'featureCustomCommandDesc',
    name: 'Özel Komutlar',
    description: 'Kendi özel komutlarınızı oluşturun ve yönetin.',
  },
  {
    slug: 'embed-message',
    titleKey: 'featureEmbed',
    descKey: 'featureEmbedDesc',
    name: 'Embed Mesaj',
    description: 'Özelleştirilebilir embed mesajlar oluşturun ve gönderin.',
  },
  {
    slug: 'giveaway',
    titleKey: 'featureGiveaway',
    descKey: 'featureGiveawayDesc',
    name: 'Çekiliş',
    description: 'Etkileşimli çekilişler düzenleyin ve kazananları otomatik seçin.',
  },
  {
    slug: 'welcome',
    titleKey: 'featureWelcome',
    descKey: 'featureWelcomeDesc',
    name: 'Hoş Geldin',
    description: 'Yeni üyelere hoş geldin mesajı, kart ve isteğe bağlı rol tanımlayın.',
  },
  {
    slug: 'goodbye',
    titleKey: 'featureGoodbye',
    descKey: 'featureGoodbyeDesc',
    name: 'Hoşça Kal',
    description: 'Ayrılan üyelere özel uğurlama ve log akışı oluşturun.',
  },
  {
    slug: 'level',
    titleKey: 'featureLevel',
    descKey: 'featureLevelDesc',
    name: 'Level Sistemi',
    description: 'Sohbette XP, seviye, rol ödülleri ve liderlik tablosu kullanın.',
  },
  {
    slug: 'music',
    titleKey: 'featureMusic',
    descKey: 'featureMusicDesc',
    name: 'Müzik',
    description: 'Kuyruk, oynatıcı kontrolleri ve geçerli oynatıcı göstergeleri sunun.',
  },
  {
    slug: 'moderator',
    titleKey: 'featureModerator',
    descKey: 'featureModeratorDesc',
    name: 'Moderasyon',
    description: 'Moderasyon logları ve ekip yönetimiyle sunucu güvenliğini destekleyin.',
  },
  {
    slug: 'ai-moderation',
    titleKey: 'featureAIModeration',
    descKey: 'featureAIModerationDesc',
    name: 'AI Moderasyon',
    description: 'Politika bazlı inceleme kuyruğu ve karar akışlarıyla riskli mesajları yönetin.',
  },
  {
    slug: 'feeds',
    titleKey: 'featureFeeds',
    descKey: 'featureFeedsDesc',
    name: 'Feed Duyuruları',
    description: 'RSS/Atom kaynaklarını takip edip yeni içerikleri Discord kanallarına duyurun.',
  },
  {
    slug: 'scheduled-announcements',
    titleKey: 'featureScheduledAnnouncements',
    descKey: 'featureScheduledAnnouncementsDesc',
    name: 'Zamanlanmış Duyurular',
    description: 'Tek seferlik veya tekrarlı duyuruları bot worker ile zamanında gönderin.',
  },
  {
    slug: 'invite-leaderboard',
    titleKey: 'featureInviteLeaderboard',
    descKey: 'featureInviteLeaderboardDesc',
    name: 'Davet Liderliği',
    description: 'Invite katkılarını ve dönemsel liderlik tablolarını takip edin.',
  },
  {
    slug: 'audit-logs',
    titleKey: 'featureAuditLogs',
    descKey: 'featureAuditLogsDesc',
    name: 'Denetim Kayıtları',
    description: 'Panel değişikliklerini actor, kaynak ve before/after diff ile izleyin.',
  },
  {
    slug: 'statistics',
    titleKey: 'featureStatistics',
    descKey: 'featureStatisticsDesc',
    name: 'İstatistik Kanalları',
    description: 'Üye, kanal ve rol sayıları için otomatik güncellenen sayaçlar oluşturun.',
  },
  {
    slug: 'custom-bots',
    titleKey: 'featureCustomBots',
    descKey: 'featureCustomBotsDesc',
    name: 'Custom Botlar',
    description: 'Kendi uygulaman ve token’ınla markalı bot kullan.',
  },
  {
    slug: 'uptime',
    titleKey: 'featureUptime',
    descKey: 'featureUptimeDesc',
    name: '7/24 Çalışma',
    description: 'Kesintisiz hizmet ile Deveng Bot her zaman sunucunuzun yanında olur.',
  },
] as const

export type LandingFeatureSlug = (typeof LANDING_FEATURES)[number]['slug']

/** İngilizce SEO / JSON-LD / sunucu taraflı özet metinleri (panel UI i18n ile ayrı). */
export const LANDING_FEATURE_SEO_EN: Record<
  LandingFeatureSlug,
  { title: string; line: string }
> = {
  poll: { title: 'Polls', line: 'Polls: create polls and collect community feedback.' },
  reminder: { title: 'Reminders', line: 'Reminders: track important dates and events.' },
  'reaction-role': { title: 'Reaction roles', line: 'Reaction roles: assign roles automatically with emojis.' },
  'temporary-voice': {
    title: 'Temporary voice',
    line: 'Temporary voice channels: lock, hide, set limits, and manage access.',
  },
  ticket: { title: 'Tickets', line: 'Tickets: automated support channels for your staff.' },
  birthday: { title: 'Birthdays', line: 'Birthdays: celebrate members automatically.' },
  logs: { title: 'Logging', line: 'Logging: follow server events in dedicated log channels.' },
  'custom-command': { title: 'Custom commands', line: 'Custom commands: build and manage your own commands.' },
  'embed-message': { title: 'Embed messages', line: 'Embed messages: rich, customizable announcements.' },
  giveaway: { title: 'Giveaways', line: 'Giveaways: run campaigns and pick winners automatically.' },
  welcome: { title: 'Welcome', line: 'Welcome flows: cards, messages, and optional auto-roles.' },
  goodbye: { title: 'Goodbye', line: 'Goodbye messages and leave logging for departing members.' },
  level: { title: 'Levels & XP', line: 'Levels & XP: chat XP, roles, and leaderboards.' },
  music: { title: 'Music', line: 'Music: queues, playback controls, and now playing.' },
  moderator: { title: 'Moderation', line: 'Moderation: staff tools and moderation logs.' },
  'ai-moderation': {
    title: 'AI moderation',
    line: 'AI moderation: review queues and workflows for risky messages.',
  },
  feeds: { title: 'Feeds', line: 'Feeds: follow RSS/Atom sources and announce new posts.' },
  'scheduled-announcements': {
    title: 'Scheduled announcements',
    line: 'Scheduled announcements: one-off or recurring posts via the bot worker.',
  },
  'invite-leaderboard': {
    title: 'Invite leaderboard',
    line: 'Invite leaderboard: track invite contributions and seasonal rankings.',
  },
  'audit-logs': {
    title: 'Audit logs',
    line: 'Audit logs: panel changes with actor, resource, and before/after diffs.',
  },
  statistics: {
    title: 'Stat channels',
    line: 'Stat channels: auto-updated counters for members, channels, and roles.',
  },
  'custom-bots': {
    title: 'Custom bot',
    line: 'Custom bot: run a branded bot with your own application and token.',
  },
  uptime: { title: 'Uptime', line: 'Reliable hosting so Deveng stays online for your community.' },
}

