/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSelectServerRouteImport } from './routes/_authenticated/select-server'
import { Route as publicTermsRouteImport } from './routes/(public)/terms'
import { Route as publicStatusRouteImport } from './routes/(public)/status'
import { Route as publicSecurityRouteImport } from './routes/(public)/security'
import { Route as publicPrivacyRouteImport } from './routes/(public)/privacy'
import { Route as publicGdprRouteImport } from './routes/(public)/gdpr'
import { Route as publicFeaturesRouteImport } from './routes/(public)/features'
import { Route as publicFaqRouteImport } from './routes/(public)/faq'
import { Route as publicEulaRouteImport } from './routes/(public)/eula'
import { Route as publicDocsRouteImport } from './routes/(public)/docs'
import { Route as publicCopyrightRouteImport } from './routes/(public)/copyright'
import { Route as publicCookiesRouteImport } from './routes/(public)/cookies'
import { Route as publicCommandsRouteImport } from './routes/(public)/commands'
import { Route as publicAboutRouteImport } from './routes/(public)/about'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedDashboardGuildIdRouteRouteImport } from './routes/_authenticated/dashboard/$guildId/route'
import { Route as AuthenticatedDashboardGuildIdIndexRouteImport } from './routes/_authenticated/dashboard/$guildId/index'
import { Route as AuthenticatedDashboardGuildIdWelcomeRouteImport } from './routes/_authenticated/dashboard/$guildId/welcome'
import { Route as AuthenticatedDashboardGuildIdTicketsRouteImport } from './routes/_authenticated/dashboard/$guildId/tickets'
import { Route as AuthenticatedDashboardGuildIdGuildAnalyticsRouteImport } from './routes/_authenticated/dashboard/$guildId/guild-analytics'
import { Route as AuthenticatedDashboardGuildIdBotWelcomeRouteImport } from './routes/_authenticated/dashboard/$guildId/bot-welcome'
import { Route as AuthenticatedDashboardGuildIdBotTicketPanelRouteImport } from './routes/_authenticated/dashboard/$guildId/bot-ticket-panel'
import { Route as AuthenticatedDashboardGuildIdBotTemporaryVoiceChannelRouteImport } from './routes/_authenticated/dashboard/$guildId/bot-temporary-voice-channel'
import { Route as AuthenticatedDashboardGuildIdBotStatisticsChannelRouteImport } from './routes/_authenticated/dashboard/$guildId/bot-statistics-channel'
import { Route as AuthenticatedDashboardGuildIdBotScheduledAnnouncementRouteImport } from './routes/_authenticated/dashboard/$guildId/bot-scheduled-announcement'
import { Route as AuthenticatedDashboardGuildIdBotReportsRouteImport } from './routes/_authenticated/dashboard/$guildId/bot-reports'
import { Route as AuthenticatedDashboardGuildIdBotReminderRouteImport } from './routes/_authenticated/dashboard/$guildId/bot-reminder'
import { Route as AuthenticatedDashboardGuildIdBotReactionRoleRouteImport } from './routes/_authenticated/dashboard/$guildId/bot-reaction-role'
import { Route as AuthenticatedDashboardGuildIdBotPrivateBotRouteImport } from './routes/_authenticated/dashboard/$guildId/bot-private-bot'
import { Route as AuthenticatedDashboardGuildIdBotPollRouteImport } from './routes/_authenticated/dashboard/$guildId/bot-poll'
import { Route as AuthenticatedDashboardGuildIdBotMusicRouteImport } from './routes/_authenticated/dashboard/$guildId/bot-music'
import { Route as AuthenticatedDashboardGuildIdBotModeratorRouteImport } from './routes/_authenticated/dashboard/$guildId/bot-moderator'
import { Route as AuthenticatedDashboardGuildIdBotModerationLogsRouteImport } from './routes/_authenticated/dashboard/$guildId/bot-moderation-logs'
import { Route as AuthenticatedDashboardGuildIdBotLogChannelRouteImport } from './routes/_authenticated/dashboard/$guildId/bot-log-channel'
import { Route as AuthenticatedDashboardGuildIdBotLocaleRouteImport } from './routes/_authenticated/dashboard/$guildId/bot-locale'
import { Route as AuthenticatedDashboardGuildIdBotLevelRouteImport } from './routes/_authenticated/dashboard/$guildId/bot-level'
import { Route as AuthenticatedDashboardGuildIdBotInviteLeaderboardRouteImport } from './routes/_authenticated/dashboard/$guildId/bot-invite-leaderboard'
import { Route as AuthenticatedDashboardGuildIdBotGoodbyeRouteImport } from './routes/_authenticated/dashboard/$guildId/bot-goodbye'
import { Route as AuthenticatedDashboardGuildIdBotGiveawayRouteImport } from './routes/_authenticated/dashboard/$guildId/bot-giveaway'
import { Route as AuthenticatedDashboardGuildIdBotFeedsRouteImport } from './routes/_authenticated/dashboard/$guildId/bot-feeds'
import { Route as AuthenticatedDashboardGuildIdBotEmbedMessageRouteImport } from './routes/_authenticated/dashboard/$guildId/bot-embed-message'
import { Route as AuthenticatedDashboardGuildIdBotCustomCommandRouteImport } from './routes/_authenticated/dashboard/$guildId/bot-custom-command'
import { Route as AuthenticatedDashboardGuildIdBotCustomBotsRouteImport } from './routes/_authenticated/dashboard/$guildId/bot-custom-bots'
import { Route as AuthenticatedDashboardGuildIdBotBirthdayRouteImport } from './routes/_authenticated/dashboard/$guildId/bot-birthday'
import { Route as AuthenticatedDashboardGuildIdBotAutoroleRouteImport } from './routes/_authenticated/dashboard/$guildId/bot-autorole'
import { Route as AuthenticatedDashboardGuildIdBotAutomationRouteImport } from './routes/_authenticated/dashboard/$guildId/bot-automation'
import { Route as AuthenticatedDashboardGuildIdBotAuditLogsRouteImport } from './routes/_authenticated/dashboard/$guildId/bot-audit-logs'
import { Route as AuthenticatedDashboardGuildIdBotAiModerationRouteImport } from './routes/_authenticated/dashboard/$guildId/bot-ai-moderation'
import { Route as authAuthSpotifyCallbackRouteImport } from './routes/(auth)/auth/spotify/callback'
import { Route as authAuthDiscordCallbackRouteImport } from './routes/(auth)/auth/discord/callback'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSelectServerRoute =
  AuthenticatedSelectServerRouteImport.update({
    id: '/select-server',
    path: '/select-server',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const publicTermsRoute = publicTermsRouteImport.update({
  id: '/(public)/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const publicStatusRoute = publicStatusRouteImport.update({
  id: '/(public)/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const publicSecurityRoute = publicSecurityRouteImport.update({
  id: '/(public)/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const publicPrivacyRoute = publicPrivacyRouteImport.update({
  id: '/(public)/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const publicGdprRoute = publicGdprRouteImport.update({
  id: '/(public)/gdpr',
  path: '/gdpr',
  getParentRoute: () => rootRouteImport,
} as any)
const publicFeaturesRoute = publicFeaturesRouteImport.update({
  id: '/(public)/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const publicFaqRoute = publicFaqRouteImport.update({
  id: '/(public)/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const publicEulaRoute = publicEulaRouteImport.update({
  id: '/(public)/eula',
  path: '/eula',
  getParentRoute: () => rootRouteImport,
} as any)
const publicDocsRoute = publicDocsRouteImport.update({
  id: '/(public)/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const publicCopyrightRoute = publicCopyrightRouteImport.update({
  id: '/(public)/copyright',
  path: '/copyright',
  getParentRoute: () => rootRouteImport,
} as any)
const publicCookiesRoute = publicCookiesRouteImport.update({
  id: '/(public)/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const publicCommandsRoute = publicCommandsRouteImport.update({
  id: '/(public)/commands',
  path: '/commands',
  getParentRoute: () => rootRouteImport,
} as any)
const publicAboutRoute = publicAboutRouteImport.update({
  id: '/(public)/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardGuildIdRouteRoute =
  AuthenticatedDashboardGuildIdRouteRouteImport.update({
    id: '/dashboard/$guildId',
    path: '/dashboard/$guildId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardGuildIdIndexRoute =
  AuthenticatedDashboardGuildIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardGuildIdRouteRoute,
  } as any)
const AuthenticatedDashboardGuildIdWelcomeRoute =
  AuthenticatedDashboardGuildIdWelcomeRouteImport.update({
    id: '/welcome',
    path: '/welcome',
    getParentRoute: () => AuthenticatedDashboardGuildIdRouteRoute,
  } as any)
const AuthenticatedDashboardGuildIdTicketsRoute =
  AuthenticatedDashboardGuildIdTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AuthenticatedDashboardGuildIdRouteRoute,
  } as any)
const AuthenticatedDashboardGuildIdGuildAnalyticsRoute =
  AuthenticatedDashboardGuildIdGuildAnalyticsRouteImport.update({
    id: '/guild-analytics',
    path: '/guild-analytics',
    getParentRoute: () => AuthenticatedDashboardGuildIdRouteRoute,
  } as any)
const AuthenticatedDashboardGuildIdBotWelcomeRoute =
  AuthenticatedDashboardGuildIdBotWelcomeRouteImport.update({
    id: '/bot-welcome',
    path: '/bot-welcome',
    getParentRoute: () => AuthenticatedDashboardGuildIdRouteRoute,
  } as any)
const AuthenticatedDashboardGuildIdBotTicketPanelRoute =
  AuthenticatedDashboardGuildIdBotTicketPanelRouteImport.update({
    id: '/bot-ticket-panel',
    path: '/bot-ticket-panel',
    getParentRoute: () => AuthenticatedDashboardGuildIdRouteRoute,
  } as any)
const AuthenticatedDashboardGuildIdBotTemporaryVoiceChannelRoute =
  AuthenticatedDashboardGuildIdBotTemporaryVoiceChannelRouteImport.update({
    id: '/bot-temporary-voice-channel',
    path: '/bot-temporary-voice-channel',
    getParentRoute: () => AuthenticatedDashboardGuildIdRouteRoute,
  } as any)
const AuthenticatedDashboardGuildIdBotStatisticsChannelRoute =
  AuthenticatedDashboardGuildIdBotStatisticsChannelRouteImport.update({
    id: '/bot-statistics-channel',
    path: '/bot-statistics-channel',
    getParentRoute: () => AuthenticatedDashboardGuildIdRouteRoute,
  } as any)
const AuthenticatedDashboardGuildIdBotScheduledAnnouncementRoute =
  AuthenticatedDashboardGuildIdBotScheduledAnnouncementRouteImport.update({
    id: '/bot-scheduled-announcement',
    path: '/bot-scheduled-announcement',
    getParentRoute: () => AuthenticatedDashboardGuildIdRouteRoute,
  } as any)
const AuthenticatedDashboardGuildIdBotReportsRoute =
  AuthenticatedDashboardGuildIdBotReportsRouteImport.update({
    id: '/bot-reports',
    path: '/bot-reports',
    getParentRoute: () => AuthenticatedDashboardGuildIdRouteRoute,
  } as any)
const AuthenticatedDashboardGuildIdBotReminderRoute =
  AuthenticatedDashboardGuildIdBotReminderRouteImport.update({
    id: '/bot-reminder',
    path: '/bot-reminder',
    getParentRoute: () => AuthenticatedDashboardGuildIdRouteRoute,
  } as any)
const AuthenticatedDashboardGuildIdBotReactionRoleRoute =
  AuthenticatedDashboardGuildIdBotReactionRoleRouteImport.update({
    id: '/bot-reaction-role',
    path: '/bot-reaction-role',
    getParentRoute: () => AuthenticatedDashboardGuildIdRouteRoute,
  } as any)
const AuthenticatedDashboardGuildIdBotPrivateBotRoute =
  AuthenticatedDashboardGuildIdBotPrivateBotRouteImport.update({
    id: '/bot-private-bot',
    path: '/bot-private-bot',
    getParentRoute: () => AuthenticatedDashboardGuildIdRouteRoute,
  } as any)
const AuthenticatedDashboardGuildIdBotPollRoute =
  AuthenticatedDashboardGuildIdBotPollRouteImport.update({
    id: '/bot-poll',
    path: '/bot-poll',
    getParentRoute: () => AuthenticatedDashboardGuildIdRouteRoute,
  } as any)
const AuthenticatedDashboardGuildIdBotMusicRoute =
  AuthenticatedDashboardGuildIdBotMusicRouteImport.update({
    id: '/bot-music',
    path: '/bot-music',
    getParentRoute: () => AuthenticatedDashboardGuildIdRouteRoute,
  } as any)
const AuthenticatedDashboardGuildIdBotModeratorRoute =
  AuthenticatedDashboardGuildIdBotModeratorRouteImport.update({
    id: '/bot-moderator',
    path: '/bot-moderator',
    getParentRoute: () => AuthenticatedDashboardGuildIdRouteRoute,
  } as any)
const AuthenticatedDashboardGuildIdBotModerationLogsRoute =
  AuthenticatedDashboardGuildIdBotModerationLogsRouteImport.update({
    id: '/bot-moderation-logs',
    path: '/bot-moderation-logs',
    getParentRoute: () => AuthenticatedDashboardGuildIdRouteRoute,
  } as any)
const AuthenticatedDashboardGuildIdBotLogChannelRoute =
  AuthenticatedDashboardGuildIdBotLogChannelRouteImport.update({
    id: '/bot-log-channel',
    path: '/bot-log-channel',
    getParentRoute: () => AuthenticatedDashboardGuildIdRouteRoute,
  } as any)
const AuthenticatedDashboardGuildIdBotLocaleRoute =
  AuthenticatedDashboardGuildIdBotLocaleRouteImport.update({
    id: '/bot-locale',
    path: '/bot-locale',
    getParentRoute: () => AuthenticatedDashboardGuildIdRouteRoute,
  } as any)
const AuthenticatedDashboardGuildIdBotLevelRoute =
  AuthenticatedDashboardGuildIdBotLevelRouteImport.update({
    id: '/bot-level',
    path: '/bot-level',
    getParentRoute: () => AuthenticatedDashboardGuildIdRouteRoute,
  } as any)
const AuthenticatedDashboardGuildIdBotInviteLeaderboardRoute =
  AuthenticatedDashboardGuildIdBotInviteLeaderboardRouteImport.update({
    id: '/bot-invite-leaderboard',
    path: '/bot-invite-leaderboard',
    getParentRoute: () => AuthenticatedDashboardGuildIdRouteRoute,
  } as any)
const AuthenticatedDashboardGuildIdBotGoodbyeRoute =
  AuthenticatedDashboardGuildIdBotGoodbyeRouteImport.update({
    id: '/bot-goodbye',
    path: '/bot-goodbye',
    getParentRoute: () => AuthenticatedDashboardGuildIdRouteRoute,
  } as any)
const AuthenticatedDashboardGuildIdBotGiveawayRoute =
  AuthenticatedDashboardGuildIdBotGiveawayRouteImport.update({
    id: '/bot-giveaway',
    path: '/bot-giveaway',
    getParentRoute: () => AuthenticatedDashboardGuildIdRouteRoute,
  } as any)
const AuthenticatedDashboardGuildIdBotFeedsRoute =
  AuthenticatedDashboardGuildIdBotFeedsRouteImport.update({
    id: '/bot-feeds',
    path: '/bot-feeds',
    getParentRoute: () => AuthenticatedDashboardGuildIdRouteRoute,
  } as any)
const AuthenticatedDashboardGuildIdBotEmbedMessageRoute =
  AuthenticatedDashboardGuildIdBotEmbedMessageRouteImport.update({
    id: '/bot-embed-message',
    path: '/bot-embed-message',
    getParentRoute: () => AuthenticatedDashboardGuildIdRouteRoute,
  } as any)
const AuthenticatedDashboardGuildIdBotCustomCommandRoute =
  AuthenticatedDashboardGuildIdBotCustomCommandRouteImport.update({
    id: '/bot-custom-command',
    path: '/bot-custom-command',
    getParentRoute: () => AuthenticatedDashboardGuildIdRouteRoute,
  } as any)
const AuthenticatedDashboardGuildIdBotCustomBotsRoute =
  AuthenticatedDashboardGuildIdBotCustomBotsRouteImport.update({
    id: '/bot-custom-bots',
    path: '/bot-custom-bots',
    getParentRoute: () => AuthenticatedDashboardGuildIdRouteRoute,
  } as any)
const AuthenticatedDashboardGuildIdBotBirthdayRoute =
  AuthenticatedDashboardGuildIdBotBirthdayRouteImport.update({
    id: '/bot-birthday',
    path: '/bot-birthday',
    getParentRoute: () => AuthenticatedDashboardGuildIdRouteRoute,
  } as any)
const AuthenticatedDashboardGuildIdBotAutoroleRoute =
  AuthenticatedDashboardGuildIdBotAutoroleRouteImport.update({
    id: '/bot-autorole',
    path: '/bot-autorole',
    getParentRoute: () => AuthenticatedDashboardGuildIdRouteRoute,
  } as any)
const AuthenticatedDashboardGuildIdBotAutomationRoute =
  AuthenticatedDashboardGuildIdBotAutomationRouteImport.update({
    id: '/bot-automation',
    path: '/bot-automation',
    getParentRoute: () => AuthenticatedDashboardGuildIdRouteRoute,
  } as any)
const AuthenticatedDashboardGuildIdBotAuditLogsRoute =
  AuthenticatedDashboardGuildIdBotAuditLogsRouteImport.update({
    id: '/bot-audit-logs',
    path: '/bot-audit-logs',
    getParentRoute: () => AuthenticatedDashboardGuildIdRouteRoute,
  } as any)
const AuthenticatedDashboardGuildIdBotAiModerationRoute =
  AuthenticatedDashboardGuildIdBotAiModerationRouteImport.update({
    id: '/bot-ai-moderation',
    path: '/bot-ai-moderation',
    getParentRoute: () => AuthenticatedDashboardGuildIdRouteRoute,
  } as any)
const authAuthSpotifyCallbackRoute = authAuthSpotifyCallbackRouteImport.update({
  id: '/(auth)/auth/spotify/callback',
  path: '/auth/spotify/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthDiscordCallbackRoute = authAuthDiscordCallbackRouteImport.update({
  id: '/(auth)/auth/discord/callback',
  path: '/auth/discord/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/about': typeof publicAboutRoute
  '/commands': typeof publicCommandsRoute
  '/cookies': typeof publicCookiesRoute
  '/copyright': typeof publicCopyrightRoute
  '/docs': typeof publicDocsRoute
  '/eula': typeof publicEulaRoute
  '/faq': typeof publicFaqRoute
  '/features': typeof publicFeaturesRoute
  '/gdpr': typeof publicGdprRoute
  '/privacy': typeof publicPrivacyRoute
  '/security': typeof publicSecurityRoute
  '/status': typeof publicStatusRoute
  '/terms': typeof publicTermsRoute
  '/select-server': typeof AuthenticatedSelectServerRoute
  '/dashboard/$guildId': typeof AuthenticatedDashboardGuildIdRouteRouteWithChildren
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/apps/': typeof AuthenticatedAppsIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/auth/discord/callback': typeof authAuthDiscordCallbackRoute
  '/auth/spotify/callback': typeof authAuthSpotifyCallbackRoute
  '/dashboard/$guildId/bot-ai-moderation': typeof AuthenticatedDashboardGuildIdBotAiModerationRoute
  '/dashboard/$guildId/bot-audit-logs': typeof AuthenticatedDashboardGuildIdBotAuditLogsRoute
  '/dashboard/$guildId/bot-automation': typeof AuthenticatedDashboardGuildIdBotAutomationRoute
  '/dashboard/$guildId/bot-autorole': typeof AuthenticatedDashboardGuildIdBotAutoroleRoute
  '/dashboard/$guildId/bot-birthday': typeof AuthenticatedDashboardGuildIdBotBirthdayRoute
  '/dashboard/$guildId/bot-custom-bots': typeof AuthenticatedDashboardGuildIdBotCustomBotsRoute
  '/dashboard/$guildId/bot-custom-command': typeof AuthenticatedDashboardGuildIdBotCustomCommandRoute
  '/dashboard/$guildId/bot-embed-message': typeof AuthenticatedDashboardGuildIdBotEmbedMessageRoute
  '/dashboard/$guildId/bot-feeds': typeof AuthenticatedDashboardGuildIdBotFeedsRoute
  '/dashboard/$guildId/bot-giveaway': typeof AuthenticatedDashboardGuildIdBotGiveawayRoute
  '/dashboard/$guildId/bot-goodbye': typeof AuthenticatedDashboardGuildIdBotGoodbyeRoute
  '/dashboard/$guildId/bot-invite-leaderboard': typeof AuthenticatedDashboardGuildIdBotInviteLeaderboardRoute
  '/dashboard/$guildId/bot-level': typeof AuthenticatedDashboardGuildIdBotLevelRoute
  '/dashboard/$guildId/bot-locale': typeof AuthenticatedDashboardGuildIdBotLocaleRoute
  '/dashboard/$guildId/bot-log-channel': typeof AuthenticatedDashboardGuildIdBotLogChannelRoute
  '/dashboard/$guildId/bot-moderation-logs': typeof AuthenticatedDashboardGuildIdBotModerationLogsRoute
  '/dashboard/$guildId/bot-moderator': typeof AuthenticatedDashboardGuildIdBotModeratorRoute
  '/dashboard/$guildId/bot-music': typeof AuthenticatedDashboardGuildIdBotMusicRoute
  '/dashboard/$guildId/bot-poll': typeof AuthenticatedDashboardGuildIdBotPollRoute
  '/dashboard/$guildId/bot-private-bot': typeof AuthenticatedDashboardGuildIdBotPrivateBotRoute
  '/dashboard/$guildId/bot-reaction-role': typeof AuthenticatedDashboardGuildIdBotReactionRoleRoute
  '/dashboard/$guildId/bot-reminder': typeof AuthenticatedDashboardGuildIdBotReminderRoute
  '/dashboard/$guildId/bot-reports': typeof AuthenticatedDashboardGuildIdBotReportsRoute
  '/dashboard/$guildId/bot-scheduled-announcement': typeof AuthenticatedDashboardGuildIdBotScheduledAnnouncementRoute
  '/dashboard/$guildId/bot-statistics-channel': typeof AuthenticatedDashboardGuildIdBotStatisticsChannelRoute
  '/dashboard/$guildId/bot-temporary-voice-channel': typeof AuthenticatedDashboardGuildIdBotTemporaryVoiceChannelRoute
  '/dashboard/$guildId/bot-ticket-panel': typeof AuthenticatedDashboardGuildIdBotTicketPanelRoute
  '/dashboard/$guildId/bot-welcome': typeof AuthenticatedDashboardGuildIdBotWelcomeRoute
  '/dashboard/$guildId/guild-analytics': typeof AuthenticatedDashboardGuildIdGuildAnalyticsRoute
  '/dashboard/$guildId/tickets': typeof AuthenticatedDashboardGuildIdTicketsRoute
  '/dashboard/$guildId/welcome': typeof AuthenticatedDashboardGuildIdWelcomeRoute
  '/dashboard/$guildId/': typeof AuthenticatedDashboardGuildIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/about': typeof publicAboutRoute
  '/commands': typeof publicCommandsRoute
  '/cookies': typeof publicCookiesRoute
  '/copyright': typeof publicCopyrightRoute
  '/docs': typeof publicDocsRoute
  '/eula': typeof publicEulaRoute
  '/faq': typeof publicFaqRoute
  '/features': typeof publicFeaturesRoute
  '/gdpr': typeof publicGdprRoute
  '/privacy': typeof publicPrivacyRoute
  '/security': typeof publicSecurityRoute
  '/status': typeof publicStatusRoute
  '/terms': typeof publicTermsRoute
  '/select-server': typeof AuthenticatedSelectServerRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/auth/discord/callback': typeof authAuthDiscordCallbackRoute
  '/auth/spotify/callback': typeof authAuthSpotifyCallbackRoute
  '/dashboard/$guildId/bot-ai-moderation': typeof AuthenticatedDashboardGuildIdBotAiModerationRoute
  '/dashboard/$guildId/bot-audit-logs': typeof AuthenticatedDashboardGuildIdBotAuditLogsRoute
  '/dashboard/$guildId/bot-automation': typeof AuthenticatedDashboardGuildIdBotAutomationRoute
  '/dashboard/$guildId/bot-autorole': typeof AuthenticatedDashboardGuildIdBotAutoroleRoute
  '/dashboard/$guildId/bot-birthday': typeof AuthenticatedDashboardGuildIdBotBirthdayRoute
  '/dashboard/$guildId/bot-custom-bots': typeof AuthenticatedDashboardGuildIdBotCustomBotsRoute
  '/dashboard/$guildId/bot-custom-command': typeof AuthenticatedDashboardGuildIdBotCustomCommandRoute
  '/dashboard/$guildId/bot-embed-message': typeof AuthenticatedDashboardGuildIdBotEmbedMessageRoute
  '/dashboard/$guildId/bot-feeds': typeof AuthenticatedDashboardGuildIdBotFeedsRoute
  '/dashboard/$guildId/bot-giveaway': typeof AuthenticatedDashboardGuildIdBotGiveawayRoute
  '/dashboard/$guildId/bot-goodbye': typeof AuthenticatedDashboardGuildIdBotGoodbyeRoute
  '/dashboard/$guildId/bot-invite-leaderboard': typeof AuthenticatedDashboardGuildIdBotInviteLeaderboardRoute
  '/dashboard/$guildId/bot-level': typeof AuthenticatedDashboardGuildIdBotLevelRoute
  '/dashboard/$guildId/bot-locale': typeof AuthenticatedDashboardGuildIdBotLocaleRoute
  '/dashboard/$guildId/bot-log-channel': typeof AuthenticatedDashboardGuildIdBotLogChannelRoute
  '/dashboard/$guildId/bot-moderation-logs': typeof AuthenticatedDashboardGuildIdBotModerationLogsRoute
  '/dashboard/$guildId/bot-moderator': typeof AuthenticatedDashboardGuildIdBotModeratorRoute
  '/dashboard/$guildId/bot-music': typeof AuthenticatedDashboardGuildIdBotMusicRoute
  '/dashboard/$guildId/bot-poll': typeof AuthenticatedDashboardGuildIdBotPollRoute
  '/dashboard/$guildId/bot-private-bot': typeof AuthenticatedDashboardGuildIdBotPrivateBotRoute
  '/dashboard/$guildId/bot-reaction-role': typeof AuthenticatedDashboardGuildIdBotReactionRoleRoute
  '/dashboard/$guildId/bot-reminder': typeof AuthenticatedDashboardGuildIdBotReminderRoute
  '/dashboard/$guildId/bot-reports': typeof AuthenticatedDashboardGuildIdBotReportsRoute
  '/dashboard/$guildId/bot-scheduled-announcement': typeof AuthenticatedDashboardGuildIdBotScheduledAnnouncementRoute
  '/dashboard/$guildId/bot-statistics-channel': typeof AuthenticatedDashboardGuildIdBotStatisticsChannelRoute
  '/dashboard/$guildId/bot-temporary-voice-channel': typeof AuthenticatedDashboardGuildIdBotTemporaryVoiceChannelRoute
  '/dashboard/$guildId/bot-ticket-panel': typeof AuthenticatedDashboardGuildIdBotTicketPanelRoute
  '/dashboard/$guildId/bot-welcome': typeof AuthenticatedDashboardGuildIdBotWelcomeRoute
  '/dashboard/$guildId/guild-analytics': typeof AuthenticatedDashboardGuildIdGuildAnalyticsRoute
  '/dashboard/$guildId/tickets': typeof AuthenticatedDashboardGuildIdTicketsRoute
  '/dashboard/$guildId/welcome': typeof AuthenticatedDashboardGuildIdWelcomeRoute
  '/dashboard/$guildId': typeof AuthenticatedDashboardGuildIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/(public)/about': typeof publicAboutRoute
  '/(public)/commands': typeof publicCommandsRoute
  '/(public)/cookies': typeof publicCookiesRoute
  '/(public)/copyright': typeof publicCopyrightRoute
  '/(public)/docs': typeof publicDocsRoute
  '/(public)/eula': typeof publicEulaRoute
  '/(public)/faq': typeof publicFaqRoute
  '/(public)/features': typeof publicFeaturesRoute
  '/(public)/gdpr': typeof publicGdprRoute
  '/(public)/privacy': typeof publicPrivacyRoute
  '/(public)/security': typeof publicSecurityRoute
  '/(public)/status': typeof publicStatusRoute
  '/(public)/terms': typeof publicTermsRoute
  '/_authenticated/select-server': typeof AuthenticatedSelectServerRoute
  '/_authenticated/dashboard/$guildId': typeof AuthenticatedDashboardGuildIdRouteRouteWithChildren
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/(auth)/auth/discord/callback': typeof authAuthDiscordCallbackRoute
  '/(auth)/auth/spotify/callback': typeof authAuthSpotifyCallbackRoute
  '/_authenticated/dashboard/$guildId/bot-ai-moderation': typeof AuthenticatedDashboardGuildIdBotAiModerationRoute
  '/_authenticated/dashboard/$guildId/bot-audit-logs': typeof AuthenticatedDashboardGuildIdBotAuditLogsRoute
  '/_authenticated/dashboard/$guildId/bot-automation': typeof AuthenticatedDashboardGuildIdBotAutomationRoute
  '/_authenticated/dashboard/$guildId/bot-autorole': typeof AuthenticatedDashboardGuildIdBotAutoroleRoute
  '/_authenticated/dashboard/$guildId/bot-birthday': typeof AuthenticatedDashboardGuildIdBotBirthdayRoute
  '/_authenticated/dashboard/$guildId/bot-custom-bots': typeof AuthenticatedDashboardGuildIdBotCustomBotsRoute
  '/_authenticated/dashboard/$guildId/bot-custom-command': typeof AuthenticatedDashboardGuildIdBotCustomCommandRoute
  '/_authenticated/dashboard/$guildId/bot-embed-message': typeof AuthenticatedDashboardGuildIdBotEmbedMessageRoute
  '/_authenticated/dashboard/$guildId/bot-feeds': typeof AuthenticatedDashboardGuildIdBotFeedsRoute
  '/_authenticated/dashboard/$guildId/bot-giveaway': typeof AuthenticatedDashboardGuildIdBotGiveawayRoute
  '/_authenticated/dashboard/$guildId/bot-goodbye': typeof AuthenticatedDashboardGuildIdBotGoodbyeRoute
  '/_authenticated/dashboard/$guildId/bot-invite-leaderboard': typeof AuthenticatedDashboardGuildIdBotInviteLeaderboardRoute
  '/_authenticated/dashboard/$guildId/bot-level': typeof AuthenticatedDashboardGuildIdBotLevelRoute
  '/_authenticated/dashboard/$guildId/bot-locale': typeof AuthenticatedDashboardGuildIdBotLocaleRoute
  '/_authenticated/dashboard/$guildId/bot-log-channel': typeof AuthenticatedDashboardGuildIdBotLogChannelRoute
  '/_authenticated/dashboard/$guildId/bot-moderation-logs': typeof AuthenticatedDashboardGuildIdBotModerationLogsRoute
  '/_authenticated/dashboard/$guildId/bot-moderator': typeof AuthenticatedDashboardGuildIdBotModeratorRoute
  '/_authenticated/dashboard/$guildId/bot-music': typeof AuthenticatedDashboardGuildIdBotMusicRoute
  '/_authenticated/dashboard/$guildId/bot-poll': typeof AuthenticatedDashboardGuildIdBotPollRoute
  '/_authenticated/dashboard/$guildId/bot-private-bot': typeof AuthenticatedDashboardGuildIdBotPrivateBotRoute
  '/_authenticated/dashboard/$guildId/bot-reaction-role': typeof AuthenticatedDashboardGuildIdBotReactionRoleRoute
  '/_authenticated/dashboard/$guildId/bot-reminder': typeof AuthenticatedDashboardGuildIdBotReminderRoute
  '/_authenticated/dashboard/$guildId/bot-reports': typeof AuthenticatedDashboardGuildIdBotReportsRoute
  '/_authenticated/dashboard/$guildId/bot-scheduled-announcement': typeof AuthenticatedDashboardGuildIdBotScheduledAnnouncementRoute
  '/_authenticated/dashboard/$guildId/bot-statistics-channel': typeof AuthenticatedDashboardGuildIdBotStatisticsChannelRoute
  '/_authenticated/dashboard/$guildId/bot-temporary-voice-channel': typeof AuthenticatedDashboardGuildIdBotTemporaryVoiceChannelRoute
  '/_authenticated/dashboard/$guildId/bot-ticket-panel': typeof AuthenticatedDashboardGuildIdBotTicketPanelRoute
  '/_authenticated/dashboard/$guildId/bot-welcome': typeof AuthenticatedDashboardGuildIdBotWelcomeRoute
  '/_authenticated/dashboard/$guildId/guild-analytics': typeof AuthenticatedDashboardGuildIdGuildAnalyticsRoute
  '/_authenticated/dashboard/$guildId/tickets': typeof AuthenticatedDashboardGuildIdTicketsRoute
  '/_authenticated/dashboard/$guildId/welcome': typeof AuthenticatedDashboardGuildIdWelcomeRoute
  '/_authenticated/dashboard/$guildId/': typeof AuthenticatedDashboardGuildIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/about'
    | '/commands'
    | '/cookies'
    | '/copyright'
    | '/docs'
    | '/eula'
    | '/faq'
    | '/features'
    | '/gdpr'
    | '/privacy'
    | '/security'
    | '/status'
    | '/terms'
    | '/select-server'
    | '/dashboard/$guildId'
    | '/errors/$error'
    | '/apps/'
    | '/dashboard/'
    | '/auth/discord/callback'
    | '/auth/spotify/callback'
    | '/dashboard/$guildId/bot-ai-moderation'
    | '/dashboard/$guildId/bot-audit-logs'
    | '/dashboard/$guildId/bot-automation'
    | '/dashboard/$guildId/bot-autorole'
    | '/dashboard/$guildId/bot-birthday'
    | '/dashboard/$guildId/bot-custom-bots'
    | '/dashboard/$guildId/bot-custom-command'
    | '/dashboard/$guildId/bot-embed-message'
    | '/dashboard/$guildId/bot-feeds'
    | '/dashboard/$guildId/bot-giveaway'
    | '/dashboard/$guildId/bot-goodbye'
    | '/dashboard/$guildId/bot-invite-leaderboard'
    | '/dashboard/$guildId/bot-level'
    | '/dashboard/$guildId/bot-locale'
    | '/dashboard/$guildId/bot-log-channel'
    | '/dashboard/$guildId/bot-moderation-logs'
    | '/dashboard/$guildId/bot-moderator'
    | '/dashboard/$guildId/bot-music'
    | '/dashboard/$guildId/bot-poll'
    | '/dashboard/$guildId/bot-private-bot'
    | '/dashboard/$guildId/bot-reaction-role'
    | '/dashboard/$guildId/bot-reminder'
    | '/dashboard/$guildId/bot-reports'
    | '/dashboard/$guildId/bot-scheduled-announcement'
    | '/dashboard/$guildId/bot-statistics-channel'
    | '/dashboard/$guildId/bot-temporary-voice-channel'
    | '/dashboard/$guildId/bot-ticket-panel'
    | '/dashboard/$guildId/bot-welcome'
    | '/dashboard/$guildId/guild-analytics'
    | '/dashboard/$guildId/tickets'
    | '/dashboard/$guildId/welcome'
    | '/dashboard/$guildId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/about'
    | '/commands'
    | '/cookies'
    | '/copyright'
    | '/docs'
    | '/eula'
    | '/faq'
    | '/features'
    | '/gdpr'
    | '/privacy'
    | '/security'
    | '/status'
    | '/terms'
    | '/select-server'
    | '/errors/$error'
    | '/apps'
    | '/dashboard'
    | '/auth/discord/callback'
    | '/auth/spotify/callback'
    | '/dashboard/$guildId/bot-ai-moderation'
    | '/dashboard/$guildId/bot-audit-logs'
    | '/dashboard/$guildId/bot-automation'
    | '/dashboard/$guildId/bot-autorole'
    | '/dashboard/$guildId/bot-birthday'
    | '/dashboard/$guildId/bot-custom-bots'
    | '/dashboard/$guildId/bot-custom-command'
    | '/dashboard/$guildId/bot-embed-message'
    | '/dashboard/$guildId/bot-feeds'
    | '/dashboard/$guildId/bot-giveaway'
    | '/dashboard/$guildId/bot-goodbye'
    | '/dashboard/$guildId/bot-invite-leaderboard'
    | '/dashboard/$guildId/bot-level'
    | '/dashboard/$guildId/bot-locale'
    | '/dashboard/$guildId/bot-log-channel'
    | '/dashboard/$guildId/bot-moderation-logs'
    | '/dashboard/$guildId/bot-moderator'
    | '/dashboard/$guildId/bot-music'
    | '/dashboard/$guildId/bot-poll'
    | '/dashboard/$guildId/bot-private-bot'
    | '/dashboard/$guildId/bot-reaction-role'
    | '/dashboard/$guildId/bot-reminder'
    | '/dashboard/$guildId/bot-reports'
    | '/dashboard/$guildId/bot-scheduled-announcement'
    | '/dashboard/$guildId/bot-statistics-channel'
    | '/dashboard/$guildId/bot-temporary-voice-channel'
    | '/dashboard/$guildId/bot-ticket-panel'
    | '/dashboard/$guildId/bot-welcome'
    | '/dashboard/$guildId/guild-analytics'
    | '/dashboard/$guildId/tickets'
    | '/dashboard/$guildId/welcome'
    | '/dashboard/$guildId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/(public)/about'
    | '/(public)/commands'
    | '/(public)/cookies'
    | '/(public)/copyright'
    | '/(public)/docs'
    | '/(public)/eula'
    | '/(public)/faq'
    | '/(public)/features'
    | '/(public)/gdpr'
    | '/(public)/privacy'
    | '/(public)/security'
    | '/(public)/status'
    | '/(public)/terms'
    | '/_authenticated/select-server'
    | '/_authenticated/dashboard/$guildId'
    | '/_authenticated/errors/$error'
    | '/_authenticated/apps/'
    | '/_authenticated/dashboard/'
    | '/(auth)/auth/discord/callback'
    | '/(auth)/auth/spotify/callback'
    | '/_authenticated/dashboard/$guildId/bot-ai-moderation'
    | '/_authenticated/dashboard/$guildId/bot-audit-logs'
    | '/_authenticated/dashboard/$guildId/bot-automation'
    | '/_authenticated/dashboard/$guildId/bot-autorole'
    | '/_authenticated/dashboard/$guildId/bot-birthday'
    | '/_authenticated/dashboard/$guildId/bot-custom-bots'
    | '/_authenticated/dashboard/$guildId/bot-custom-command'
    | '/_authenticated/dashboard/$guildId/bot-embed-message'
    | '/_authenticated/dashboard/$guildId/bot-feeds'
    | '/_authenticated/dashboard/$guildId/bot-giveaway'
    | '/_authenticated/dashboard/$guildId/bot-goodbye'
    | '/_authenticated/dashboard/$guildId/bot-invite-leaderboard'
    | '/_authenticated/dashboard/$guildId/bot-level'
    | '/_authenticated/dashboard/$guildId/bot-locale'
    | '/_authenticated/dashboard/$guildId/bot-log-channel'
    | '/_authenticated/dashboard/$guildId/bot-moderation-logs'
    | '/_authenticated/dashboard/$guildId/bot-moderator'
    | '/_authenticated/dashboard/$guildId/bot-music'
    | '/_authenticated/dashboard/$guildId/bot-poll'
    | '/_authenticated/dashboard/$guildId/bot-private-bot'
    | '/_authenticated/dashboard/$guildId/bot-reaction-role'
    | '/_authenticated/dashboard/$guildId/bot-reminder'
    | '/_authenticated/dashboard/$guildId/bot-reports'
    | '/_authenticated/dashboard/$guildId/bot-scheduled-announcement'
    | '/_authenticated/dashboard/$guildId/bot-statistics-channel'
    | '/_authenticated/dashboard/$guildId/bot-temporary-voice-channel'
    | '/_authenticated/dashboard/$guildId/bot-ticket-panel'
    | '/_authenticated/dashboard/$guildId/bot-welcome'
    | '/_authenticated/dashboard/$guildId/guild-analytics'
    | '/_authenticated/dashboard/$guildId/tickets'
    | '/_authenticated/dashboard/$guildId/welcome'
    | '/_authenticated/dashboard/$guildId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  publicAboutRoute: typeof publicAboutRoute
  publicCommandsRoute: typeof publicCommandsRoute
  publicCookiesRoute: typeof publicCookiesRoute
  publicCopyrightRoute: typeof publicCopyrightRoute
  publicDocsRoute: typeof publicDocsRoute
  publicEulaRoute: typeof publicEulaRoute
  publicFaqRoute: typeof publicFaqRoute
  publicFeaturesRoute: typeof publicFeaturesRoute
  publicGdprRoute: typeof publicGdprRoute
  publicPrivacyRoute: typeof publicPrivacyRoute
  publicSecurityRoute: typeof publicSecurityRoute
  publicStatusRoute: typeof publicStatusRoute
  publicTermsRoute: typeof publicTermsRoute
  authAuthDiscordCallbackRoute: typeof authAuthDiscordCallbackRoute
  authAuthSpotifyCallbackRoute: typeof authAuthSpotifyCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/select-server': {
      id: '/_authenticated/select-server'
      path: '/select-server'
      fullPath: '/select-server'
      preLoaderRoute: typeof AuthenticatedSelectServerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(public)/terms': {
      id: '/(public)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof publicTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/status': {
      id: '/(public)/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof publicStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/security': {
      id: '/(public)/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof publicSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/privacy': {
      id: '/(public)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof publicPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/gdpr': {
      id: '/(public)/gdpr'
      path: '/gdpr'
      fullPath: '/gdpr'
      preLoaderRoute: typeof publicGdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/features': {
      id: '/(public)/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof publicFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/faq': {
      id: '/(public)/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof publicFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/eula': {
      id: '/(public)/eula'
      path: '/eula'
      fullPath: '/eula'
      preLoaderRoute: typeof publicEulaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/docs': {
      id: '/(public)/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof publicDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/copyright': {
      id: '/(public)/copyright'
      path: '/copyright'
      fullPath: '/copyright'
      preLoaderRoute: typeof publicCopyrightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/cookies': {
      id: '/(public)/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof publicCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/commands': {
      id: '/(public)/commands'
      path: '/commands'
      fullPath: '/commands'
      preLoaderRoute: typeof publicCommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/about': {
      id: '/(public)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof publicAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/$guildId': {
      id: '/_authenticated/dashboard/$guildId'
      path: '/dashboard/$guildId'
      fullPath: '/dashboard/$guildId'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/$guildId/': {
      id: '/_authenticated/dashboard/$guildId/'
      path: '/'
      fullPath: '/dashboard/$guildId/'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRouteRoute
    }
    '/_authenticated/dashboard/$guildId/welcome': {
      id: '/_authenticated/dashboard/$guildId/welcome'
      path: '/welcome'
      fullPath: '/dashboard/$guildId/welcome'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdWelcomeRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRouteRoute
    }
    '/_authenticated/dashboard/$guildId/tickets': {
      id: '/_authenticated/dashboard/$guildId/tickets'
      path: '/tickets'
      fullPath: '/dashboard/$guildId/tickets'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdTicketsRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRouteRoute
    }
    '/_authenticated/dashboard/$guildId/guild-analytics': {
      id: '/_authenticated/dashboard/$guildId/guild-analytics'
      path: '/guild-analytics'
      fullPath: '/dashboard/$guildId/guild-analytics'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdGuildAnalyticsRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRouteRoute
    }
    '/_authenticated/dashboard/$guildId/bot-welcome': {
      id: '/_authenticated/dashboard/$guildId/bot-welcome'
      path: '/bot-welcome'
      fullPath: '/dashboard/$guildId/bot-welcome'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdBotWelcomeRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRouteRoute
    }
    '/_authenticated/dashboard/$guildId/bot-ticket-panel': {
      id: '/_authenticated/dashboard/$guildId/bot-ticket-panel'
      path: '/bot-ticket-panel'
      fullPath: '/dashboard/$guildId/bot-ticket-panel'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdBotTicketPanelRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRouteRoute
    }
    '/_authenticated/dashboard/$guildId/bot-temporary-voice-channel': {
      id: '/_authenticated/dashboard/$guildId/bot-temporary-voice-channel'
      path: '/bot-temporary-voice-channel'
      fullPath: '/dashboard/$guildId/bot-temporary-voice-channel'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdBotTemporaryVoiceChannelRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRouteRoute
    }
    '/_authenticated/dashboard/$guildId/bot-statistics-channel': {
      id: '/_authenticated/dashboard/$guildId/bot-statistics-channel'
      path: '/bot-statistics-channel'
      fullPath: '/dashboard/$guildId/bot-statistics-channel'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdBotStatisticsChannelRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRouteRoute
    }
    '/_authenticated/dashboard/$guildId/bot-scheduled-announcement': {
      id: '/_authenticated/dashboard/$guildId/bot-scheduled-announcement'
      path: '/bot-scheduled-announcement'
      fullPath: '/dashboard/$guildId/bot-scheduled-announcement'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdBotScheduledAnnouncementRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRouteRoute
    }
    '/_authenticated/dashboard/$guildId/bot-reports': {
      id: '/_authenticated/dashboard/$guildId/bot-reports'
      path: '/bot-reports'
      fullPath: '/dashboard/$guildId/bot-reports'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdBotReportsRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRouteRoute
    }
    '/_authenticated/dashboard/$guildId/bot-reminder': {
      id: '/_authenticated/dashboard/$guildId/bot-reminder'
      path: '/bot-reminder'
      fullPath: '/dashboard/$guildId/bot-reminder'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdBotReminderRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRouteRoute
    }
    '/_authenticated/dashboard/$guildId/bot-reaction-role': {
      id: '/_authenticated/dashboard/$guildId/bot-reaction-role'
      path: '/bot-reaction-role'
      fullPath: '/dashboard/$guildId/bot-reaction-role'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdBotReactionRoleRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRouteRoute
    }
    '/_authenticated/dashboard/$guildId/bot-private-bot': {
      id: '/_authenticated/dashboard/$guildId/bot-private-bot'
      path: '/bot-private-bot'
      fullPath: '/dashboard/$guildId/bot-private-bot'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdBotPrivateBotRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRouteRoute
    }
    '/_authenticated/dashboard/$guildId/bot-poll': {
      id: '/_authenticated/dashboard/$guildId/bot-poll'
      path: '/bot-poll'
      fullPath: '/dashboard/$guildId/bot-poll'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdBotPollRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRouteRoute
    }
    '/_authenticated/dashboard/$guildId/bot-music': {
      id: '/_authenticated/dashboard/$guildId/bot-music'
      path: '/bot-music'
      fullPath: '/dashboard/$guildId/bot-music'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdBotMusicRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRouteRoute
    }
    '/_authenticated/dashboard/$guildId/bot-moderator': {
      id: '/_authenticated/dashboard/$guildId/bot-moderator'
      path: '/bot-moderator'
      fullPath: '/dashboard/$guildId/bot-moderator'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdBotModeratorRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRouteRoute
    }
    '/_authenticated/dashboard/$guildId/bot-moderation-logs': {
      id: '/_authenticated/dashboard/$guildId/bot-moderation-logs'
      path: '/bot-moderation-logs'
      fullPath: '/dashboard/$guildId/bot-moderation-logs'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdBotModerationLogsRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRouteRoute
    }
    '/_authenticated/dashboard/$guildId/bot-log-channel': {
      id: '/_authenticated/dashboard/$guildId/bot-log-channel'
      path: '/bot-log-channel'
      fullPath: '/dashboard/$guildId/bot-log-channel'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdBotLogChannelRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRouteRoute
    }
    '/_authenticated/dashboard/$guildId/bot-locale': {
      id: '/_authenticated/dashboard/$guildId/bot-locale'
      path: '/bot-locale'
      fullPath: '/dashboard/$guildId/bot-locale'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdBotLocaleRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRouteRoute
    }
    '/_authenticated/dashboard/$guildId/bot-level': {
      id: '/_authenticated/dashboard/$guildId/bot-level'
      path: '/bot-level'
      fullPath: '/dashboard/$guildId/bot-level'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdBotLevelRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRouteRoute
    }
    '/_authenticated/dashboard/$guildId/bot-invite-leaderboard': {
      id: '/_authenticated/dashboard/$guildId/bot-invite-leaderboard'
      path: '/bot-invite-leaderboard'
      fullPath: '/dashboard/$guildId/bot-invite-leaderboard'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdBotInviteLeaderboardRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRouteRoute
    }
    '/_authenticated/dashboard/$guildId/bot-goodbye': {
      id: '/_authenticated/dashboard/$guildId/bot-goodbye'
      path: '/bot-goodbye'
      fullPath: '/dashboard/$guildId/bot-goodbye'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdBotGoodbyeRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRouteRoute
    }
    '/_authenticated/dashboard/$guildId/bot-giveaway': {
      id: '/_authenticated/dashboard/$guildId/bot-giveaway'
      path: '/bot-giveaway'
      fullPath: '/dashboard/$guildId/bot-giveaway'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdBotGiveawayRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRouteRoute
    }
    '/_authenticated/dashboard/$guildId/bot-feeds': {
      id: '/_authenticated/dashboard/$guildId/bot-feeds'
      path: '/bot-feeds'
      fullPath: '/dashboard/$guildId/bot-feeds'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdBotFeedsRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRouteRoute
    }
    '/_authenticated/dashboard/$guildId/bot-embed-message': {
      id: '/_authenticated/dashboard/$guildId/bot-embed-message'
      path: '/bot-embed-message'
      fullPath: '/dashboard/$guildId/bot-embed-message'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdBotEmbedMessageRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRouteRoute
    }
    '/_authenticated/dashboard/$guildId/bot-custom-command': {
      id: '/_authenticated/dashboard/$guildId/bot-custom-command'
      path: '/bot-custom-command'
      fullPath: '/dashboard/$guildId/bot-custom-command'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdBotCustomCommandRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRouteRoute
    }
    '/_authenticated/dashboard/$guildId/bot-custom-bots': {
      id: '/_authenticated/dashboard/$guildId/bot-custom-bots'
      path: '/bot-custom-bots'
      fullPath: '/dashboard/$guildId/bot-custom-bots'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdBotCustomBotsRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRouteRoute
    }
    '/_authenticated/dashboard/$guildId/bot-birthday': {
      id: '/_authenticated/dashboard/$guildId/bot-birthday'
      path: '/bot-birthday'
      fullPath: '/dashboard/$guildId/bot-birthday'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdBotBirthdayRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRouteRoute
    }
    '/_authenticated/dashboard/$guildId/bot-autorole': {
      id: '/_authenticated/dashboard/$guildId/bot-autorole'
      path: '/bot-autorole'
      fullPath: '/dashboard/$guildId/bot-autorole'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdBotAutoroleRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRouteRoute
    }
    '/_authenticated/dashboard/$guildId/bot-automation': {
      id: '/_authenticated/dashboard/$guildId/bot-automation'
      path: '/bot-automation'
      fullPath: '/dashboard/$guildId/bot-automation'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdBotAutomationRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRouteRoute
    }
    '/_authenticated/dashboard/$guildId/bot-audit-logs': {
      id: '/_authenticated/dashboard/$guildId/bot-audit-logs'
      path: '/bot-audit-logs'
      fullPath: '/dashboard/$guildId/bot-audit-logs'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdBotAuditLogsRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRouteRoute
    }
    '/_authenticated/dashboard/$guildId/bot-ai-moderation': {
      id: '/_authenticated/dashboard/$guildId/bot-ai-moderation'
      path: '/bot-ai-moderation'
      fullPath: '/dashboard/$guildId/bot-ai-moderation'
      preLoaderRoute: typeof AuthenticatedDashboardGuildIdBotAiModerationRouteImport
      parentRoute: typeof AuthenticatedDashboardGuildIdRouteRoute
    }
    '/(auth)/auth/spotify/callback': {
      id: '/(auth)/auth/spotify/callback'
      path: '/auth/spotify/callback'
      fullPath: '/auth/spotify/callback'
      preLoaderRoute: typeof authAuthSpotifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/auth/discord/callback': {
      id: '/(auth)/auth/discord/callback'
      path: '/auth/discord/callback'
      fullPath: '/auth/discord/callback'
      preLoaderRoute: typeof authAuthDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedDashboardGuildIdRouteRouteChildren {
  AuthenticatedDashboardGuildIdBotAiModerationRoute: typeof AuthenticatedDashboardGuildIdBotAiModerationRoute
  AuthenticatedDashboardGuildIdBotAuditLogsRoute: typeof AuthenticatedDashboardGuildIdBotAuditLogsRoute
  AuthenticatedDashboardGuildIdBotAutomationRoute: typeof AuthenticatedDashboardGuildIdBotAutomationRoute
  AuthenticatedDashboardGuildIdBotAutoroleRoute: typeof AuthenticatedDashboardGuildIdBotAutoroleRoute
  AuthenticatedDashboardGuildIdBotBirthdayRoute: typeof AuthenticatedDashboardGuildIdBotBirthdayRoute
  AuthenticatedDashboardGuildIdBotCustomBotsRoute: typeof AuthenticatedDashboardGuildIdBotCustomBotsRoute
  AuthenticatedDashboardGuildIdBotCustomCommandRoute: typeof AuthenticatedDashboardGuildIdBotCustomCommandRoute
  AuthenticatedDashboardGuildIdBotEmbedMessageRoute: typeof AuthenticatedDashboardGuildIdBotEmbedMessageRoute
  AuthenticatedDashboardGuildIdBotFeedsRoute: typeof AuthenticatedDashboardGuildIdBotFeedsRoute
  AuthenticatedDashboardGuildIdBotGiveawayRoute: typeof AuthenticatedDashboardGuildIdBotGiveawayRoute
  AuthenticatedDashboardGuildIdBotGoodbyeRoute: typeof AuthenticatedDashboardGuildIdBotGoodbyeRoute
  AuthenticatedDashboardGuildIdBotInviteLeaderboardRoute: typeof AuthenticatedDashboardGuildIdBotInviteLeaderboardRoute
  AuthenticatedDashboardGuildIdBotLevelRoute: typeof AuthenticatedDashboardGuildIdBotLevelRoute
  AuthenticatedDashboardGuildIdBotLocaleRoute: typeof AuthenticatedDashboardGuildIdBotLocaleRoute
  AuthenticatedDashboardGuildIdBotLogChannelRoute: typeof AuthenticatedDashboardGuildIdBotLogChannelRoute
  AuthenticatedDashboardGuildIdBotModerationLogsRoute: typeof AuthenticatedDashboardGuildIdBotModerationLogsRoute
  AuthenticatedDashboardGuildIdBotModeratorRoute: typeof AuthenticatedDashboardGuildIdBotModeratorRoute
  AuthenticatedDashboardGuildIdBotMusicRoute: typeof AuthenticatedDashboardGuildIdBotMusicRoute
  AuthenticatedDashboardGuildIdBotPollRoute: typeof AuthenticatedDashboardGuildIdBotPollRoute
  AuthenticatedDashboardGuildIdBotPrivateBotRoute: typeof AuthenticatedDashboardGuildIdBotPrivateBotRoute
  AuthenticatedDashboardGuildIdBotReactionRoleRoute: typeof AuthenticatedDashboardGuildIdBotReactionRoleRoute
  AuthenticatedDashboardGuildIdBotReminderRoute: typeof AuthenticatedDashboardGuildIdBotReminderRoute
  AuthenticatedDashboardGuildIdBotReportsRoute: typeof AuthenticatedDashboardGuildIdBotReportsRoute
  AuthenticatedDashboardGuildIdBotScheduledAnnouncementRoute: typeof AuthenticatedDashboardGuildIdBotScheduledAnnouncementRoute
  AuthenticatedDashboardGuildIdBotStatisticsChannelRoute: typeof AuthenticatedDashboardGuildIdBotStatisticsChannelRoute
  AuthenticatedDashboardGuildIdBotTemporaryVoiceChannelRoute: typeof AuthenticatedDashboardGuildIdBotTemporaryVoiceChannelRoute
  AuthenticatedDashboardGuildIdBotTicketPanelRoute: typeof AuthenticatedDashboardGuildIdBotTicketPanelRoute
  AuthenticatedDashboardGuildIdBotWelcomeRoute: typeof AuthenticatedDashboardGuildIdBotWelcomeRoute
  AuthenticatedDashboardGuildIdGuildAnalyticsRoute: typeof AuthenticatedDashboardGuildIdGuildAnalyticsRoute
  AuthenticatedDashboardGuildIdTicketsRoute: typeof AuthenticatedDashboardGuildIdTicketsRoute
  AuthenticatedDashboardGuildIdWelcomeRoute: typeof AuthenticatedDashboardGuildIdWelcomeRoute
  AuthenticatedDashboardGuildIdIndexRoute: typeof AuthenticatedDashboardGuildIdIndexRoute
}

const AuthenticatedDashboardGuildIdRouteRouteChildren: AuthenticatedDashboardGuildIdRouteRouteChildren =
  {
    AuthenticatedDashboardGuildIdBotAiModerationRoute:
      AuthenticatedDashboardGuildIdBotAiModerationRoute,
    AuthenticatedDashboardGuildIdBotAuditLogsRoute:
      AuthenticatedDashboardGuildIdBotAuditLogsRoute,
    AuthenticatedDashboardGuildIdBotAutomationRoute:
      AuthenticatedDashboardGuildIdBotAutomationRoute,
    AuthenticatedDashboardGuildIdBotAutoroleRoute:
      AuthenticatedDashboardGuildIdBotAutoroleRoute,
    AuthenticatedDashboardGuildIdBotBirthdayRoute:
      AuthenticatedDashboardGuildIdBotBirthdayRoute,
    AuthenticatedDashboardGuildIdBotCustomBotsRoute:
      AuthenticatedDashboardGuildIdBotCustomBotsRoute,
    AuthenticatedDashboardGuildIdBotCustomCommandRoute:
      AuthenticatedDashboardGuildIdBotCustomCommandRoute,
    AuthenticatedDashboardGuildIdBotEmbedMessageRoute:
      AuthenticatedDashboardGuildIdBotEmbedMessageRoute,
    AuthenticatedDashboardGuildIdBotFeedsRoute:
      AuthenticatedDashboardGuildIdBotFeedsRoute,
    AuthenticatedDashboardGuildIdBotGiveawayRoute:
      AuthenticatedDashboardGuildIdBotGiveawayRoute,
    AuthenticatedDashboardGuildIdBotGoodbyeRoute:
      AuthenticatedDashboardGuildIdBotGoodbyeRoute,
    AuthenticatedDashboardGuildIdBotInviteLeaderboardRoute:
      AuthenticatedDashboardGuildIdBotInviteLeaderboardRoute,
    AuthenticatedDashboardGuildIdBotLevelRoute:
      AuthenticatedDashboardGuildIdBotLevelRoute,
    AuthenticatedDashboardGuildIdBotLocaleRoute:
      AuthenticatedDashboardGuildIdBotLocaleRoute,
    AuthenticatedDashboardGuildIdBotLogChannelRoute:
      AuthenticatedDashboardGuildIdBotLogChannelRoute,
    AuthenticatedDashboardGuildIdBotModerationLogsRoute:
      AuthenticatedDashboardGuildIdBotModerationLogsRoute,
    AuthenticatedDashboardGuildIdBotModeratorRoute:
      AuthenticatedDashboardGuildIdBotModeratorRoute,
    AuthenticatedDashboardGuildIdBotMusicRoute:
      AuthenticatedDashboardGuildIdBotMusicRoute,
    AuthenticatedDashboardGuildIdBotPollRoute:
      AuthenticatedDashboardGuildIdBotPollRoute,
    AuthenticatedDashboardGuildIdBotPrivateBotRoute:
      AuthenticatedDashboardGuildIdBotPrivateBotRoute,
    AuthenticatedDashboardGuildIdBotReactionRoleRoute:
      AuthenticatedDashboardGuildIdBotReactionRoleRoute,
    AuthenticatedDashboardGuildIdBotReminderRoute:
      AuthenticatedDashboardGuildIdBotReminderRoute,
    AuthenticatedDashboardGuildIdBotReportsRoute:
      AuthenticatedDashboardGuildIdBotReportsRoute,
    AuthenticatedDashboardGuildIdBotScheduledAnnouncementRoute:
      AuthenticatedDashboardGuildIdBotScheduledAnnouncementRoute,
    AuthenticatedDashboardGuildIdBotStatisticsChannelRoute:
      AuthenticatedDashboardGuildIdBotStatisticsChannelRoute,
    AuthenticatedDashboardGuildIdBotTemporaryVoiceChannelRoute:
      AuthenticatedDashboardGuildIdBotTemporaryVoiceChannelRoute,
    AuthenticatedDashboardGuildIdBotTicketPanelRoute:
      AuthenticatedDashboardGuildIdBotTicketPanelRoute,
    AuthenticatedDashboardGuildIdBotWelcomeRoute:
      AuthenticatedDashboardGuildIdBotWelcomeRoute,
    AuthenticatedDashboardGuildIdGuildAnalyticsRoute:
      AuthenticatedDashboardGuildIdGuildAnalyticsRoute,
    AuthenticatedDashboardGuildIdTicketsRoute:
      AuthenticatedDashboardGuildIdTicketsRoute,
    AuthenticatedDashboardGuildIdWelcomeRoute:
      AuthenticatedDashboardGuildIdWelcomeRoute,
    AuthenticatedDashboardGuildIdIndexRoute:
      AuthenticatedDashboardGuildIdIndexRoute,
  }

const AuthenticatedDashboardGuildIdRouteRouteWithChildren =
  AuthenticatedDashboardGuildIdRouteRoute._addFileChildren(
    AuthenticatedDashboardGuildIdRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSelectServerRoute: typeof AuthenticatedSelectServerRoute
  AuthenticatedDashboardGuildIdRouteRoute: typeof AuthenticatedDashboardGuildIdRouteRouteWithChildren
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSelectServerRoute: AuthenticatedSelectServerRoute,
  AuthenticatedDashboardGuildIdRouteRoute:
    AuthenticatedDashboardGuildIdRouteRouteWithChildren,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  publicAboutRoute: publicAboutRoute,
  publicCommandsRoute: publicCommandsRoute,
  publicCookiesRoute: publicCookiesRoute,
  publicCopyrightRoute: publicCopyrightRoute,
  publicDocsRoute: publicDocsRoute,
  publicEulaRoute: publicEulaRoute,
  publicFaqRoute: publicFaqRoute,
  publicFeaturesRoute: publicFeaturesRoute,
  publicGdprRoute: publicGdprRoute,
  publicPrivacyRoute: publicPrivacyRoute,
  publicSecurityRoute: publicSecurityRoute,
  publicStatusRoute: publicStatusRoute,
  publicTermsRoute: publicTermsRoute,
  authAuthDiscordCallbackRoute: authAuthDiscordCallbackRoute,
  authAuthSpotifyCallbackRoute: authAuthSpotifyCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
