namespace Deveng.Discord.Api.Services;

/// <summary>Panel ile aynı sırada: her tür için Discord kanal kısa adı + embed varsayılanları.</summary>
public static class LogChannelProvisionData
{
    public sealed record Entry(
        string LogType,
        string ChannelSlug,
        string EmbedTitle,
        string EmbedDescription,
        string EmbedColor);

    public static readonly IReadOnlyList<Entry> Entries = new List<Entry>
    {
        new("MESSAGE_DELETE", "d-mesaj-sil",
            "🗑️ Mesaj Silindi",
            "{usermention} tarafından {channel} kanalında bir mesaj silindi.\n\n**Mesaj İçeriği:**\n{message}",
            "#ED4245"),
        new("MESSAGE_EDIT", "d-mesaj-duzelt",
            "✏️ Mesaj Düzenlendi",
            "{usermention} tarafından {channel} kanalında bir mesaj düzenlendi.\n\n**Eski Mesaj:**\n{oldmessage}\n\n**Yeni Mesaj:**\n{newmessage}",
            "#FEE75C"),
        new("MEMBER_BAN", "d-uyye-yasak",
            "🔨 Üye Yasaklandı",
            "{usermention} sunucudan yasaklandı.\n\n**Moderatör:** {moderator}\n**Sebep:** {reason}",
            "#ED4245"),
        new("MEMBER_KICK", "d-uyye-at",
            "👢 Üye Atıldı",
            "{usermention} sunucudan atıldı.\n\n**Moderatör:** {moderator}\n**Sebep:** {reason}",
            "#ED4245"),
        new("MEMBER_ROLE_ADD", "d-rol-ekle",
            "➕ Rol Eklendi",
            "{usermention} kullanıcısına {rolemention} rolü eklendi.\n\n**Moderatör:** {moderator}",
            "#57F287"),
        new("MEMBER_ROLE_REMOVE", "d-rol-kaldir",
            "➖ Rol Kaldırıldı",
            "{usermention} kullanıcısından {rolemention} rolü kaldırıldı.\n\n**Moderatör:** {moderator}",
            "#ED4245"),
        new("CHANNEL_CREATE", "d-knl-olustur",
            "➕ Kanal Oluşturuldu",
            "{channelmention} kanalı oluşturuldu.\n\n**Moderatör:** {moderator}",
            "#57F287"),
        new("CHANNEL_DELETE", "d-knl-sil",
            "🗑️ Kanal Silindi",
            "{channel} kanalı silindi.\n\n**Moderatör:** {moderator}",
            "#ED4245"),
        new("CHANNEL_UPDATE", "d-knl-guncelle",
            "✏️ Kanal Güncellendi",
            "{channelmention} kanalı güncellendi.\n\n**Moderatör:** {moderator}",
            "#FEE75C"),
        new("ROLE_CREATE", "d-rol-olustur",
            "➕ Rol Oluşturuldu",
            "{rolemention} rolü oluşturuldu.\n\n**Moderatör:** {moderator}",
            "#57F287"),
        new("ROLE_DELETE", "d-rol-sil",
            "🗑️ Rol Silindi",
            "{role} rolü silindi.\n\n**Moderatör:** {moderator}",
            "#ED4245"),
        new("ROLE_UPDATE", "d-rol-guncelle",
            "✏️ Rol Güncellendi",
            "{rolemention} rolü güncellendi.\n\n**Moderatör:** {moderator}",
            "#FEE75C"),
        new("MEMBER_UPDATE", "d-uyye-guncelle",
            "👤 Üye Güncellendi",
            "{usermention} kullanıcısının bilgileri güncellendi.",
            "#FEE75C"),
        new("GUILD_UPDATE", "d-sunucu-guncelle",
            "⚙️ Sunucu Güncellendi",
            "Sunucu ayarları güncellendi.\n\n**Moderatör:** {moderator}",
            "#FEE75C"),
    };
}
